### PR TITLE
Yet another Carthage support

### PR DESCRIPTION
**Pull request by mickamy**
There are some PRs trying to add Carthage support (#7 or #28).
But all of them are stale and I can no see any progress for a long time.

So I created a yet another Carthage support PR.

### CODE REVIEW

**Comment by mickamy** [comment]
@fassko Is it possible to review/merge this one?

**Comment by fassko** [comment]
@mickamy thanks for your contribution. I haven't used Carthage myself. Can you tell how to test this?

**Comment by mickamy** [comment]
Actually this PR does not work well for now.
Because of the absence of the `.xcodeproj` file in this repo.

AFAIK, Carthage searches `xcodeproj` or `xcworkspace` file in repo on running `carthage update` or some other command to install, to detect Shared scheme contained in it so that Carthage can build it.

There is an issue discussing about supporting SwiftPM managed project in Carthage though, it seems have no progress lately.
ref: https://github.com/Carthage/Carthage/issues/1226

I guess we need to manage `xcodeproj` file again to support Carthage for now.
Any though on this?

@fassko

**Comment by mickamy** [comment]
Updated PR and included .xcodeproj file to repo.
And I also created a repo that proves my implementation works fine.
https://github.com/mickamy/RxAnimatedCarthageExample

@fassko Is it enough for testing?
I can update example or whatsoever quickly, because I stay home for the COVID-19 situation.

**Comment by fassko** [comment]
Thanks @mickamy

**Pull request merged**
