### PR TITLE
Add support for RxSwift 6

### PR DESCRIPTION
**Pull request by Econa77**

### CODE REVIEW

**Comment by Econa77** [comment]
@jdisho  @fassko Would you review it?

**Comment by fassko** [comment]
Hi, @Econa77 maybe you want to help put with maintaining this project? :)

**Comment by fassko** [comment]
0.9.0 has been released with the support of RxSwift 6.0

**Comment by Econa77** [comment]
@fassko I'm using this library in some projects so I can help with maintenance 👍

**Comment by fassko** [comment]
@Econa77 OK I will try to organize access. I guess we still need the cocoapod support.

**Pull request merged**
