### PR TITLE
Example of Lazy Implementation

### PR DESCRIPTION
**Pull request by iDevid**
This is an example of lazy implementation, with also an example in the example project.

### CODE REVIEW

**Comment by iDevid** [comment]
@fassko could you review this?

**Comment by fassko** [comment]
@iDevid Can you please explain the need of such feature? Thanks!

**Comment by iDevid** [comment]
@fassko when I use with hidden binding in stack views for example. Without Lazy at startup all the binded views will be showed, then with animation they disappear do tue the data model binding. It is a bit ugly.

**Comment by fassko** [comment]
To be honest I'm a bit lost. Can you explain once again. An example would help a lot. Thanks!

Can your need be a wrapper around this library. We aim to have this library as lightweight as possible.

**Comment by iDevid** [comment]
If you run the example app, I added an example of that

**Comment by iDevid** [comment]
Can I send you an email with a real app video example? @fassko

**Comment by iDevid** [comment]
@fassko

**Pull request closed without merging**
