### PR TITLE
[WIP] initial PR

### PR DESCRIPTION
**Pull request by icanzilb**

### CODE REVIEW

**Comment by icanzilb** [comment]
As per @freak4pc suggestions:

image

**Comment by icanzilb** [comment]
image

**Comment by freak4pc** [comment]
Nice !! Looks very cool! The only thing I think this still doesn't solve is adding custom animations? `AnimationType` is still an enum but it doesn't conform to some general protocol that other animation types can implement I think ? 

Not sure though if that's still necessary as those are bind-only animations anyways so ¯\_(ツ)_/¯

**Comment by icanzilb** [comment]
@freak4pc sorry, maybe I should've been clearer in the comment :) I just added your code samples to the conversation here so we don't lose them in the Slack history :)

**Comment by icanzilb** [comment]
I'd never use a dark editor background myself :)))

**Comment by freak4pc** [comment]
Oh cool cool :) Got it 👍 
You wrote "as per suggestions" so I got confused :D 

LOL about the editor 😂

**Comment by icanzilb** [comment]
Well, this is the beta version of the initial release, elt's do it!

**Pull request merged**
